/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface EmailVerificationToken {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  person_id: string;
  token_hash: string;
  updated_at: Timestamp | null;
  verified: Generated<boolean>;
  verified_at: Timestamp | null;
}

export interface LoginAttempt {
  attempted_at: Generated<Timestamp>;
  email: string;
  failure_reason: string | null;
  id: Generated<string>;
  ip_address: string;
  success: boolean;
  user_agent: string | null;
}

export interface OauthProvider {
  access_token: string | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  person_id: string;
  provider: string;
  provider_user_id: string;
  refresh_token: string | null;
  token_expires_at: Timestamp | null;
  updated_at: Timestamp | null;
}

export interface PasswordHistory {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  password_hash: string;
  person_id: string;
  updated_at: Timestamp | null;
}

export interface PasswordResetToken {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  person_id: string;
  token_hash: string;
  updated_at: Timestamp | null;
  used: Generated<boolean>;
  used_at: Timestamp | null;
}

export interface Person {
  avatar_url: string | null;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  email: string;
  email_verified: Generated<boolean>;
  failed_login_attempts: Generated<number>;
  first_name: string | null;
  id: Generated<string>;
  is_2fa_enabled: Generated<boolean>;
  is_active: Generated<boolean>;
  last_login_at: Timestamp | null;
  last_name: string | null;
  locked_until: Timestamp | null;
  password_hash: string;
  two_fa_secret: string | null;
  updated_at: Timestamp | null;
}

export interface RefreshToken {
  created_at: Generated<Timestamp>;
  device_name: string | null;
  device_type: string | null;
  expires_at: Timestamp;
  id: Generated<string>;
  ip_address: string | null;
  is_revoked: Generated<boolean>;
  last_used_at: Timestamp | null;
  person_id: string;
  revoked_at: Timestamp | null;
  token_hash: string;
  updated_at: Timestamp | null;
  user_agent: string | null;
}

export interface TwoFaBackupCode {
  code_hash: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  person_id: string;
  updated_at: Timestamp | null;
  used: Generated<boolean>;
  used_at: Timestamp | null;
}

export interface DB {
  email_verification_token: EmailVerificationToken;
  login_attempt: LoginAttempt;
  oauth_provider: OauthProvider;
  password_history: PasswordHistory;
  password_reset_token: PasswordResetToken;
  person: Person;
  refresh_token: RefreshToken;
  two_fa_backup_code: TwoFaBackupCode;
}
